# Generated by Django 4.2.20 on 2025-03-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_system", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resetpasswordrequest",
            name="expire",
            field=models.IntegerField(default=1741621300),
        ),
        migrations.AlterField(
            model_name="resetpasswordrequest",
            name="token",
            field=models.CharField(default="44c27494f89e", max_length=50),
        ),
    ]
