# Generated by Django 4.2.20 on 2025-03-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_system", "0002_alter_resetpasswordrequest_expire_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resetpasswordrequest",
            name="expire",
            field=models.IntegerField(default=1741621303),
        ),
        migrations.AlterField(
            model_name="resetpasswordrequest",
            name="token",
            field=models.CharField(default="c84b61a00d0b", max_length=50),
        ),
    ]
