# Generated by Django 4.2.20 on 2025-03-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_system", "0006_alter_resetpasswordrequest_expire_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resetpasswordrequest",
            name="expire",
            field=models.IntegerField(default=1741622306),
        ),
        migrations.AlterField(
            model_name="resetpasswordrequest",
            name="token",
            field=models.CharField(default="be6af33440bf", max_length=50),
        ),
    ]
